macro_rules! codegens {
    ($($codegen:ident,)*) => {
        pub unsafe fn load_targets() -> Option<crate::nob::Array<crate::targets::Target>> {
            use crate::crust::libc::*;
            use crate::nob::*;
            use crate::targets::*;
            use core::mem::zeroed;
            use core::ffi::*;

            let mut targets: Array<Target> = zeroed();
            let mut apis: Array<TargetAPI> = zeroed();

            $(
                crate::codegen::$codegen::get_apis(&mut apis);
                register_apis(&mut targets, apis, c!(stringify!($codegen)))?;
                apis.count = 0;
            )*

            free(apis.items as _);
            Some(targets)
        }

        $(pub mod $codegen;)*
    };
}

include!(".INDEX.rs"); // .INDEX.rs is generated by bgen.rs
